### ISSUE TITLE
Declarations has fill date set to date of the import

### ISSUE THREAD

**Issue by dchaplinsky** [dchaplinsky/declarations.com.ua#12]
rather to the value from spreadsheet.
http://take.ms/LkpgV

**Comment by excieve** [comment]
Screenshot doesn't work:

``` xml
<Error><Code>KeyTooLongError</Code><Message>Your key is too long</Message><Size>1233</Size><MaxSizeAllowed>1024</MaxSizeAllowed><RequestId>464303C9EA0DAEA5</RequestId><HostId>ruUnVMwUCphU26UPPyjt6sfhY3miVMWaUBUMp/yFkKp9nPy9ylf6K2q+lZeESVLP</HostId></Error>
```

**Comment by excieve** [comment]
@dchaplinsky sorry can't find evidence for this locally. Could you please send me the input file that was last applied on production?

**Comment by dchaplinsky** [comment]
http://take.ms/FMcVE

**Comment by excieve** [comment]
Your screenshot tool seems to be broken :/
![screenshot at 21-45-36](https://cloud.githubusercontent.com/assets/1077193/6998075/346cc82e-dbdd-11e4-8990-17749369633f.png)

**Comment by dchaplinsky** [comment]
![- - - 2013 2015-04-05 21-43-21](https://cloud.githubusercontent.com/assets/131186/6998105/37d9396a-dbde-11e4-888f-8a6612765900.png)

**Comment by excieve** [comment]
Right, apparently date format has changed in the input file after I've loaded it last time. Will fix.

**Comment by excieve** [comment]
@dchaplinsky this requires initial data reimport.
