### ISSUE TITLE
Integrate R analytics from Kirill

### ISSUE THREAD

**Issue by dchaplinsky** [dchaplinsky/declarations.com.ua#21]
We need a way to integrate analytics that Kirill made: http://pro-media.com.ua/decs/
He is using R/knitr/knitrbootrstrap.
I think we can use following way:
- Create a django manage.py command to export ALL data into JSON format
- Invoke R from there.
- Collect results in html or markdown (and render it to html) and re-insert it into CMS.

This “offline” way will work as we only updating site once in a while with a big batch of data.
R sources are in your mailbox.

**Comment by wundervaflja** [comment]
But isn't it better option to transfer all code from R to python ( numpy or scipy tech stack) ?

**Comment by dchaplinsky** [comment]
Not sure. It requires extra work just to achieve the same. Working with R is the shortest path for now, which costs almost nothing and it'll cover 80% of our needs in static analytics. Later we can refine and also add BI.

And believe me, we have plenty of work even without analytics. Integration of data from chesno and their ios/android app to name a few.
