### ISSUE TITLE
Implement API

### ISSUE THREAD

**Issue by excieve** [dchaplinsky/declarations.com.ua#6]
All declarations along with search and filtering should be exposed via JSON API.

**Comment by excieve** [comment]
Possibly utilise [Django REST framework](http://www.django-rest-framework.org/) - has some useful batteries included.

**Comment by dchaplinsky** [comment]
My idea was more like json serialisation of ES results instead of template rendering if some param is present within GET request.

Probably with a help of decorator. Not sure if Django REST framework wouldn't be an overkill.
